[package]
name = "gflags-impl"
version = "0.3.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Macros for gflags crate"
repository = "https://github.com/dtolnay/gflags"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
